### ISSUE TITLE
End event fired multiple times

### ISSUE THREAD

**Issue by MrDHat** [nodemailer/mailparser#147]
This is what my code looks like:

``` js
  var self = this;
  self.mailParser = new MailParser({
    showAttachmentLinks: true
  });

  self.mailParser.on('headers', function (headers) {
    console.log(headers);
  });

  self.mailParser.once('end', function (mailObj) {
    console.log(mailObj);
  });

  // messageBody is returned from `node-imap`
  bufferBody = new Buffer(self.messageBody, 'utf-8');
  self.mailParser.write(bufferBody);

  self.mailParser.end();

```

The `end` event is fired multiple times(2 times to be specific) but the `headers` event is fired only once. Not sure what went wrong here.

**Comment by hsachdevah** [comment]
I am facing the problem.

**Comment by hsachdevah** [comment]
I observed that end event runs for as many times as there are is a number of "Subject:" statements in the content.

**Comment by andrewbruno** [comment]
If you remove the following code, does it still fire twice?

`  
   self.mailParser.on('headers', function (headers) {
    console.log(headers);
  });
`

**Comment by NIshantDesaiJumpbyte** [comment]
Yes  i am experiencing this issue for email threads (in gmail) which contain multiple replies.
For example if there are 3 replies in an email. Then the end event is fired 3 times with mail_object.text as the first comment + the email body.
