### ISSUE TITLE
How to use MailParser({streamAttachments: true}) with Nodemailer?

### ISSUE THREAD

**Issue by hugovart** [nodemailer/mailparser#155]
I am trying to figure out how can I use Mailparser when `streamAttachments: true` enabled with Nodemailer. 

``` javascript
parser = new MailParser({
  streamAttachments: true
});

parser.on('end', function(parsedMsg) {

  for (key = 0, len = parsedMsg.attachments; key < len; key++) {
    parsedMsg.attachments[key].filename = parsedMsg.attachments[key].fileName;
    delete parsedMsg.attachments[key].fileName;
    parsedMsg.attachments[key].content = parsedMsg.attachments[key].stream;
    delete parsedMsg.attachments[key].stream;
  }

  transport.sendMail(parsedMsg, function(err, info) {
    //CODE NEVER REACHES HERE...
  });

});

emailStream.pipe(parser);
```

**Comment by andris9** [comment]
You should probably try to resume the streams by calling parsedMsg.attachments[key].stream.resume() or something like that, I guess that Nodemailer is waiting for input from the attachment streams but it never receives anything.

Mailparser is an ancient code in the Node.js world, I guess it was written for Node v0.5 or something and as such the streaming interface is not totally compatible with the latest Node streams.

**Comment by hugovart** [comment]
`parsedMsg.attachments[key].stream.resume()` didn't do the trick: `TypeError: Object #<Base64Stream> has no method 'resume'`
Do you have a suggestion of an up to date alternative to MailParser?
