### ISSUE TITLE
empty Content-Type before name not parsed correctly

### ISSUE THREAD

**Issue by atiertant** [nodemailer/mailparser#159]
when parsing a mail containing Content-Type: ; name="test" in attachment, parser resolve ContentType to name="test"

added a test https://github.com/andris9/mailparser/pull/158

**Comment by andris9** [comment]
Thanks, this is a bug. Mailparser is quite old, I have fixed this issue in my other mail modules (see [this function](https://github.com/nodemailer/libmime/blob/c5001c58ef238a84a45f1bafd996db0e58136ccd/lib/libmime.js#L354-L478) for example), I try to backport it whenever I have time
