### ISSUE TITLE
how to save parsed email to file system

### ISSUE THREAD

**Issue by spyshow** [nodemailer/mailparser#172]
hi 
i'm writing an electron app and i have a pdf file in my system to attach and then save the email.eml to the file system and then open it  , here is my code : 

    var encodedText = "Content-type: multipart/mixed; boundary=ABC\r\n" +
                      "X-Test: =?UTF-8?Q?=C3=95=C3=84?= =?UTF-8?Q?=C3=96=C3=9C?=\r\n" +
                      "Subject:Issue ID: "+issue_id+"!\r\n"+
                      "\r\n" +
                      "--ABC\r\n" +
                      "Content-Type: application/octet-stream\r\n" +
                      "Content-Transfer-Encoding: base64\r\n" +
                      "Content-Disposition: attachment; filename=\""+app.getPath('userData')+'\\temp\\1.pdf'+"\"\r\n" +
                      "\r\n" +
                      "AAECAwQFBg==\r\n" +
                      "--ABC--",
    mail = new Buffer(encodedText, "utf-8");
    var mailparser = new MailParser();
    mailparser.end(mail);

how can i save it  to the file system ?

**Comment by spyshow** [comment]
any solution???

**Comment by Sjonnie2nd** [comment]
Hi spyshow,

You are asking this at the wrong place.

mailParser does not create emails but, the other way arround, does read them.
You might take a look at [https://github.com/nodemailer/mailcomposer](https://github.com/nodemailer/mailcomposer).
I have no experience with Electron and don't know if you can use it within Electron.

Also "how can i save it to the file system" has nothing to do with mail parsing or composing. I could point you to some node.js methods but I expect that Electron has its own implementation. 
But wait: when Googling on "Electron file" you get lots of hits. fe: [https://ourcodeworld.com/articles/read/106/how-to-choose-read-save-delete-or-create-a-file-with-electron-framework](https://ourcodeworld.com/articles/read/106/how-to-choose-read-save-delete-or-create-a-file-with-electron-framework)
