### ISSUE TITLE
html:false with 2.2.0

### ISSUE THREAD

**Issue by Sjonnie2nd** [nodemailer/mailparser#185]
Hi Andris,

After upgrading to 2.2.0 a week ago I receive lots of emails where after parsing html=false. For example all newsletters I receive from CodeProject. But also (for me very important) my own created email templates. When opening them in Outlook there's nothing wrong or changed in those emails/templates.
Going back the 2.1.0 the issue is gone.

Greetings, Ronald

**Comment by Sjonnie2nd** [comment]
An update:

The issue with the html=false only happens with emails which are only 1 node with Content-Type: text/html, Content-Transfer-Encoding: base64. My mail-templates have only 1 node because... they are templates :) 
But now everyday I receive emails from others which have the same problem.

When debugging (2.2.0) it looks like it is caused by the async processing of the streams.
At first getTextContent() is looking at node.textContent, which is empty. After it node.textContent gets filled by contentStream.once('end', () => .. ) with... the right html content.

Emails with Content-Type: multipart/alternative; are doing fine: 
At first contentStream.once('end'..) is called (a few times) and at the end getTextContent() is called.

I dont know what exactly is causing the issue. Im not that good with promisses, async processing etc..
It doesn't look to be caused by the pull requests. Perhaps by changes in dependencies like mailsplit, tlds or libbase64?

**Comment by BarryRufer** [comment]
The problem is not solved!
