### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by spectejb** [nodemailer/mailparser#188]
@nodemailer - Two license questions for you:

-Would you be willing to update to EUPL 1.2? It adds more compatible licenses in the Appendix.
-Would you be willing to dual license with MIT, BSD or Apache in case companies are more comfortable with permissive?

Both recommendations would be helpful with increasing adoption of mailparser across the board!

Thanks, in advance, for your consideration!

**Comment by andris9** [comment]
Mailparser is licensed under 1.1 or later which also covers 1.2

I’m not interested using a completely free license, I used MIT mostly in the past and all I got from it was huge amount of free help requests and about $50 in donations over a 5 year period.

**Comment by spectejb** [comment]
Thanks for confirming, @andris9! 

I am learning a lot about licenses and would love to understand more about the meaning behind not being interested in a "completely free license."  Can you help me understand what you mean by EUPL not being free?  Thanks so much!

**Comment by andris9** [comment]
@spectejb  By "completely free" I mean "almost free of any obligations" (and "almost" as there are still some obligations in MIT/BSD licenses even though these are minor ones) compared to EUPL that is more like GPL or even AGPL.

**Comment by flohdot** [comment]
Hi, I see that the rest of the nodemailer project has gone back to MIT, as per other repos and the website (https://nodemailer.com/about/license/). Is this one intentionally still using EUPL? Thanks!

**Comment by kinkoazc** [comment]
@andris9 Thank you for your activity on this repo. But why the sudden switch from MIT to EUPL? Why not EUPL from the get-go? Are contributions(in the form of direct commits, pull-requests, reported bugs, etc.) not considered a joint effort for an efficient, comprehensive and bug-free library?
