### ISSUE TITLE
Header Transformation Options

### ISSUE THREAD

**Issue by 250ok-mikeyoung** [nodemailer/mailparser#189]
Would it make sense to make the header transformations more controllable?  The problem I have is I want the raw header.  Older versions of mail parser provided the raw header value.  In my case I need the raw header value for downstream processing but I don't see an option to disable header transformations. There also doesn't seem to be a consistent pattern of what transformations return.  For example to and from header transformations return a text property that shows the raw value.  But dkim-signature just returns an object with no raw header.

**Comment by andris9** [comment]
The information is actually all there, so I changed the master branch to include `headerLines` in the response, in addition to `headers`. It's an array of all header lines, where line is a 'binary' encoded string.

```
$ node examples/simple-async.js
{ attachments: [],
  headers:
   Map {
     'from' => { value: [ { address: 'andris@kreata.ee', name: '' } ],
     html:
      '<span class="mp_address_group"><a href="mailto:andris@kreata.ee" class="mp_address_email">andris@kreata.ee</a></span>',
     text: 'andris@kreata.ee' },
     'to' => { value: [ { address: 'andris.reinman@gmail.com', name: '' } ],
     html:
      '<span class="mp_address_group"><a href="mailto:andris.reinman@gmail.com" class="mp_address_email">andris.reinman@gmail.com</a></span>',
     text: 'andris.reinman@gmail.com' },
     'subject' => 'test',
     'date' => 2017-01-08T18:37:44.000Z },
  headerLines:
   [ { key: 'from', line: 'From: andris@kreata.ee' },
     { key: 'to', line: 'To: andris.reinman@gmail.com' },
     { key: 'subject', line: 'Subject: test' },
     { key: 'date', line: 'Date: Sun, 8 Jan 2017 20:37:44 +0200' } ],
...
```

**Comment by 250ok-mikeyoung** [comment]
Thanks! I can work with this.  Any idea when this will be published as an npm package?

**Comment by andris9** [comment]
I pushed the change to npm as v2.3.4

**Comment by andris9** [comment]
And temember - this is "binary" (8bit) encoding. If you want to convert it to unicode then do something like this:

```
var unicodeStr = Buffer.from(mail.headerLines[0].line, 'binary').toString();
```
