### ISSUE TITLE
In reply to and reference starting with %3C and closing with %3E

### ISSUE THREAD

**Issue by peernohell** [nodemailer/mailparser#198]
Hey, 

We get one customer who receive an email where in-reply-to and references ids where wrapped by %3C and %3D instead of < and >.

It's the first time I see this and I didn't find any information about that.
I would like to know if you would accept a PR where ensureMessageIDFormat while check if the first char is not < if it start with %3C and replace it with < and the same with %3E with > ?

I would love to have your point of view on this

**Comment by andris9** [comment]
I guess it is ok to convert enclosing urlencoded chars to correct form. Was the entire string url encoded? Eg %40 instead of @ or only the start and ending?

**Comment by peernohell** [comment]
What is strange is it's not the case. It's looklike %3Ce42a3f99a-db3d-1873-a31f-7dded34af1bb@thedomain.com%3E
