### ISSUE TITLE
How I can extend mailparser class to support 'iso-2022-jp'

### ISSUE THREAD

**Issue by misteral** [nodemailer/mailparser#199]
How I can extend mailparser to use node-iconv. I see on previous versions you use [encoding package](https://www.npmjs.com/package/encoding) now just plain iconv-lite. How it possible to use node-iconv with v2+ versions?

**Comment by misteral** [comment]
Ping @zaach any news?

**Comment by markb-trustifi** [comment]
You can check this repository. It has some fix fo it:
https://github.com/vikaskanani/mailparser/commit/62b2dfe0e70451eff69d97ca88ca3a309245f0ed#diff-c576476d6c0cf8444152b1e5ff67fbe5

**Comment by andris9** [comment]
latest version of mailparser allows to provide node-iconv module as an alternative decoder:

```javascript
const Iconv = require('iconv').Iconv;
const MailParser = require('mailparser').MailParser;
let parser = new MailParser({ Iconv });
```

or

```javascript
const Iconv = require('iconv').Iconv;
const simpleParser = require('mailparser').simpleParser;
simpleParser('rfc822 message', { Iconv }, callback);
```
