### ISSUE TITLE
DoS vulnerability when parsing email with millions of multiparts

### ISSUE THREAD

**Issue by dylanlingelbach** [nodemailer/mailparser#202]
Per https://snyk.io/vuln/npm:mailparser:20180625, `mailparser` is vulnerable to a DoS if a specially crafted email with millions of multiparts is attempted to be parsed with the library.

I haven't had a chance to attempt to reproduce this yet, so feel free to close if there is no vulnerability.

**Comment by andris9** [comment]
this was fixed when the so-called-vulnerability was made public

**Comment by michaelfarrell76** [comment]
is there a way you can resolve this with snyk so it does not continue to report this as a high security vulnerability?
