### ISSUE TITLE
No `end` event without `data` listener

### ISSUE THREAD

**Issue by yeya** [nodemailer/mailparser#206]
Using the provided [pipe example](https://github.com/nodemailer/mailparser/blob/master/examples/pipe.js)
If I remove the `data` listener - line 20 to 56 - the `end` event does not fire at all.

**Expected behavior** 
The `end` event should be fired anyway,

**Actual behavior**
No `end` event

**Workaround**
`parser.on('data', function () {});`

**Comment by andris9** [comment]
That’s how streams in nodejs work. If you do not read from the stream, it never ends.
