### ISSUE TITLE
Cut new release with corrected LICENSE.MIT file

### ISSUE THREAD

**Issue by sbwsg** [nodemailer/mailparser#212]
Hi, I work on a project called [Deck](https://github.com/spinnaker/deck) which uses a testing library called [mountebank](https://github.com/bbyars/mountebank). Mountebank depends on a fork of mailparser ([mailparser2](https://github.com/Aredack/mailparser2)) and, transitively, mailsplit.

I'm updating Mountebank to depend on `nodemailer/mailparser` instead of the forked version.  I noticed that you recently updated the LICENSE.MIT files of both mailparser and mailsplit to correct the files' legal text. Would you be willing to cut new npm releases of these two packages so that they include the updated license contents?

**Comment by andris9** [comment]
Fixed in latest version of Mailparser
