### ISSUE TITLE
possible optimized version of simpleParser by optionally skipping readable and read only headers

### ISSUE THREAD

**Issue by ciekawy** [nodemailer/mailparser#222]
if someone wants to skip data this would allow to avoid re-implementing parser without parsing data/attachments.

the KISS version would be to add `skipReadable` option and based on it omit invoking `parser.on('readable', //...` in `simpleParser`. More advanced version can allow to skip just attachments or just text.

**Comment by andris9** [comment]
simpleParser is just a thin wrapper around mailParser, so if you have any special requirements, you could easily achieve it by using mailParser directly.

**Comment by TechAurelian** [comment]
@andris9 Can you share some sample code to read only the mail headers using mailParser?
