### ISSUE TITLE
Missing closing boundary hangs simpleparser

### ISSUE THREAD

**Issue by matteomattei** [nodemailer/mailparser#224]
We have a multipart email with a PDF attached without the trailing close boundary tag at the end of the message. This is a malformed email but this message causes the missing call of the stream end in simpleParser blocking the mail read flow.

How can we fix this?

**Comment by Patrick-Remy** [comment]
Same issue here for html attachments

**Comment by cloverb** [comment]
Reproduction here: https://repl.it/@cloverb/BountifulQuestionableDaemon

Ideally we could get some sort of timeout/error here?

**Comment by andris9** [comment]
Should be fixed in latest release
