### ISSUE TITLE
Parsing message from exchange journaling (embedded under rfc822)

### ISSUE THREAD

**Issue by mattgaspar** [nodemailer/mailparser#226]
I'm try to receive mail from Exchange journaling using nodemailer smtp-server and parse it using mailparser but the message I want to log is embedded under message/rfc822.
I want to ignore the first header and body above message/rfc822 and parse the rest as normal.
Is there any options in mailparser to do this?
I took a look at mailsplit and I was able to ignore the first nodes but it adds a bit of complexity. (I see there is an option ignoreEmbedded but I'm looking for the opposite, onlyProcessEmbedded)

Maybe I could pipe the stream through a custom function that ignored everything before rfc822 before piping it to the parser?  I don't know enough about node streams but it seems like it could be a simple solution if possible.

Here's the basic format of the message (with the header data removed):

<pre><code>Content-Type: multipart/mixed;
	boundary="_860d9182-927e-4668-a27d-084c02aca482_"
<i>HEADER FROM JOURNAL AGENT</i>

--_860d9182-927e-4668-a27d-084c02aca482_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit

Sender: 
Subject: Test
Message-Id: 
To: 

--_860d9182-927e-4668-a27d-084c02aca482_
Content-Type: message/rfc822

<i>HEADER FROM ORIGINAL MESSAGE</i>
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<i>MESSAGE BODY</i>

--_860d9182-927e-4668-a27d-084c02aca482_--

</code></pre>

**Comment by andris9** [comment]
You should probably process the messages twise. First with `ignoreEmbedded`, then look for the `message/rfc822` attachment and process it separately.
