### ISSUE TITLE
Unable to decode file attachments

### ISSUE THREAD

**Issue by LucasDachman** [nodemailer/mailparser#227]
I'm using simple parser to parse gmail messages like
```js
simpleParser(base64url.decode(rawMessage))
```

Message attributes work fine but I when I try to decode file attachments the file is corrupted. Here's how I do it:

```js
    const attachment = message.attachments[0];
    const blob = new Blob(attachment.content, {type: attachment.contentType});
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.download = attachment.filename;
    link.click();
```

The result is a nonsense file.

**Comment by andris9** [comment]
This seems to be from a browser environment, Mailparser natively supports only latest versions of Node, for everything else you're on your own - you might get it working or you might not
