### ISSUE TITLE
format=flowed disables un-quoting

### ISSUE THREAD

**Issue by tajinder** [nodemailer/mailparser#234]
A message with format=flowed and encoding "quoted-printable" is not decoded.

Content-Type: text/plain; charset=utf-8; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

> The format=3Dflowed RFC supports having lines that are explicitly meant
> not to be wrapped (they call them "fixed lines") but looks like
> many format=3Dflowed MUAs don't give you a way to write such lines
> as you compose the email...

**Comment by andris9** [comment]
Any background info on this? Any email client sending such emails?

From [rfc2646](https://tools.ietf.org/html/rfc2646#page-6)

> [Quoted-Printable] encoding SHOULD NOT be used with Format=Flowed unless absolutely necessary (for example, non-US-ASCII (8-bit) characters over a strictly 7-bit transport such as unextended SMTP). In particular, a message SHOULD NOT be encoded in Quoted-Printable for the sole purpose of protecting the trailing space on flowed lines unless the body part is cryptographically signed or encrypted

**Comment by tajinder** [comment]
Its Thunderbird still sending such emails

Date: Sun, 15 Sep 2019 04:38:57 +0000
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.8.0
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

**Comment by JohannesHub** [comment]
I have the same Issue with Emails sent by Roundcube 1.3.9.

**Comment by andris9** [comment]
Should be fixed in latest release. Flowed decoding is applied after transfer decoding.
