### ISSUE TITLE
Content-Type: multipart/mixed; boundary="PHP-mixed-7d1965c80dda1783d81760a7a55a914c" not get response

### ISSUE THREAD

**Issue by jameerjbr** [nodemailer/mailparser#236]
Content-Type: multipart/mixed; boundary="PHP-mixed-7d1965c80dda1783d81760a7a55a914c"
Date: Thu, 16 Aug 2018 12:46:48 +0200
Message-Id: <1534416408.824926.22927.nullmailer@me>

--PHP-mixed-7d1965c80dda1783d81760a7a55a914c
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

Hello,

you can download the iPhone screen resolution PDF poster here:
http://www.paintcodeapp.com/download/poster_iphones.pdf

Enjoy!

Best wishes,
PixelCut Team

--PHP-mixed-7d1965c80dda1783d81760a7a55a914c

**Comment by cloverb** [comment]
Related to https://github.com/nodemailer/mailparser/issues/224?

**Comment by jameerjbr** [comment]
> Related to #224?

`http://www.paintcodeapp.com/download/poster_iphones.pdf` not a file this normal link

**Comment by andris9** [comment]
Should be fixed in latest release
