### ISSUE TITLE
Change in attachment filenames

### ISSUE THREAD

**Issue by cloverb** [nodemailer/mailparser#238]
In older versions of mailparser, attachments without names had one generated for them with the correct file type. Repro here: https://repl.it/@cloverb/MediumorchidDishonestAddons. Note the `generatedFileName` in the output.

In the current version , attachments without names don't have a name property at all. Repro here: https://repl.it/@cloverb/SoreScientificTriggers.

Is there a reason for this change in behavior?

**Comment by andris9** [comment]
`generatedFileName` was a convenience property. Basically it is just taking the string 'attachment' and adding a suffix with the extension derived from `contentType`. Current version of Mailparser was written from the ground up and was supposed to be more leaner, so a lot of these convenience things did not make it to the code. In this sense `generatedFileName` was never removed - it was not re-implemented.
