### ISSUE TITLE
skipHtmlToText option not working

### ISSUE THREAD

**Issue by cloverb** [nodemailer/mailparser#239]
skipHtmlToText is not working in the current release even though it's in the docs: https://nodemailer.com/extras/mailparser/#options.

It looks like it's in master, but was never cut into a release: https://github.com/nodemailer/mailparser/pull/219/commits/a20ce77025598fcbfe477e6ab06ba3f78f3d2c2e.

Can we get this released?

**Comment by andris9** [comment]
Released in lates version
