### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by AdriVanHoudt** [nodemailer/mailparser#241]
Using the simpleParser on a message with Greek characters it returns the characters as �.

I discovered that if you pass just a string, simpleParser will convert it to a binary buffer https://github.com/nodemailer/mailparser/blob/master/lib/simple-parser.js#L108
Now this is the same as converting to a buffer with latin1 (see https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings)
When I pass my own buffer doing `Buffer.from(input, 'utf8')` it does properly return the characters.
I can get around this by passing my own buffer atm but this seems like a useful update to the lib?

Example Greek text to test on: `Η παραγγελία που έδωσες βρίσκεται καθ' οδόν!`

**Comment by andris9** [comment]
Yeah, I can see how it may be confusing. Historically binary strings were expected due to a lot of emails not being utf-8 but in some other codepage. I guess this behavior can be changed now as you can use Buffer for such messages.

**Comment by andris9** [comment]
Fixed and published in mailparser@2.7.6

**Comment by AdriVanHoudt** [comment]
That was quick :O thanks!

**Comment by AdriVanHoudt** [comment]
Hmm both https://github.com/nodemailer/mailparser/commit/633e4369c93dc5122c8c8bee0fd2b057761e1223 and https://github.com/nodemailer/mailparser/commit/08f17398dceb8941de5d73d538ac859e7d5e7248 seem to be the cause of this issue in the first place.
I tried to convert some gbk strings (I'm not familiar with them so might be doing something wrong here) and converting with 'utf8' seems to work while binary doesn't so not sure why these changes were made

**Comment by andris9** [comment]
I guess I did not thought this through when I accepted these PR's. The described issue probably happened in a browser as Uint8Array was used.

**Comment by AdriVanHoudt** [comment]
From what I can deduct from https://github.com/nodemailer/mailparser/pull/232 it seems like it was used in an RSS application. They pass their own Buffer now so this won't impact them I guess https://github.com/DIYgod/RSSHub/blob/master/lib/routes/mail/imap.js#L42.
Although I can't imagine it parsing correctly but I don't know the details of these things :/
