### ISSUE TITLE
When is HtmlToText used

### ISSUE THREAD

**Issue by jspruyt** [nodemailer/mailparser#243]
HI,
I'm using mailparser indirectly through nodered. In nodered I'm fetching emails from Office365 via IMAP, and the mails are being parsed by mailparser.
For some mails, there is no `text/plain` content, only `text/html` content as the first part in a `multipart/related` content block

```
Content-Type: multipart/related;
	boundary="_008_VI1PR0601MB2589338B367C06453B08BAF98F4F0VI1PR0601MB2589_";
	type="text/html"
MIME-Version: 1.0

--_008_VI1PR0601MB2589338B367C06453B08BAF98F4F0VI1PR0601MB2589_
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64

PGh0bWwgeG1sbnM6dj0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTp2bWwiIHhtbG5zOm89InVy
...
```

When this email is parsed, no plain text is generated from the html content. Is this correct?

```js
if ((!alternative && this.hasText) || (node.root && !this.hasText)) {
```
From this line of code (*getTextContent function, line 702*) I can gather that plaintext is only generated when either:
  - the multipart subtype is **not** set to "alternative" **AND** there already is plaintext in the mail
  - this is the root part **AND** there is no plaintext in the mail

Could it be forced anyway, or is there a specific reason why it is set up like this?

**Comment by andris9** [comment]
Html and plaintext are generated only if the message mime tree is built in way where some parts of the tree have only text or html but the message itself has both. This happens  for example when a signature is injected to message.

**Comment by mattgaspar** [comment]
So if the message only contains a "text/html" node, a text property is not output.
Why is there an option "skipHtmlToText - Don’t generate plaintext from HTML."?  
Based on the description it sounds like the default is to always generate plaintext from HTML.

Can you provide more clarity around the purpose of this option?

And do the options under the MailParser section apply to SimpleParser?  
Why not just list the options under each section?

https://nodemailer.com/extras/mailparser/#options

**Comment by francescosalvi** [comment]
> Why is there an option "skipHtmlToText - Don’t generate plaintext from HTML."?
I also am very confused by this documentation statement. I think it should read "Don't generate HTML from plaintext" (swapped terms).
