### ISSUE TITLE
Misdecoded Content-Disposition header

### ISSUE THREAD

**Issue by dynamicnet** [nodemailer/mailparser#244]
The header set below cause the email to be parsed without HTML content, but with an attachement that content the original HTML message.

Seems that the problem occurs when the Content-Disposition header value is encoded using "encoded-word" rules, if the header value is "inline" only, there is no problem.

> Date: Tue, 26 Nov 2019 19:14:31 +0000
MIME-Version: 1.0
Content-Type: text/html;
 charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: =?utf-8?Q?inline?=
Subject: =?utf-8?Q?SubjectRedacted?=
To: =?utf-8?Q?Redacted?= <email@redacted>
From: =?utf-8?Q?Redacted?= <recipient@redacted>

**Comment by cwill** [comment]
@andris9 Hi! I encountered this bug today in packaged version 2.7.7, which it looks like is the latest one available via npm. Do you know when a release containing this fix might be available? Thanks!

**Comment by dynamicnet** [comment]
@cwill I use 2.7.7 in production and I have not encountered again the exact same issue.
