### ISSUE TITLE
optional mailparser for browser

### ISSUE THREAD

**Issue by nutphi** [nodemailer/mailparser#248]
I found a mailparser library that andris9 recommended to use in browsers on the [thread](https://github.com/nodemailer/mailparser/issues/129)
I'm not sure if the library's already obsolete or not and the one I want to use **emailjs-mime-parser**.
It said 'Felix is not actively maintaining this library anymore' and last update was 6 months ago.
I would like to make sure if it is still good to use the lib or not.

**Comment by holtwick** [comment]
I also want to use it in the browser. I added this on line to workaround the only problem I found so far:

```js
window.setImmediate = fn => setTimeout(fn, 0)
```

**Comment by andris9** [comment]
mailparser does not officially support running in browsers. It might work though, haven't tested.
