### ISSUE TITLE
How to combine smtp-server and mailparser

### ISSUE THREAD

**Issue by ceraz68** [nodemailer/mailparser#250]
I'm trying to capture the subject and contents of incoming mails to my smtp-server on node.js. In the old days mailparser was able to retrieve both values within the same scope now I'm confused with the two separate events (headers and data). Can someone help me out with the below sample code, how can I recover the subject and text for later processing within the onData function of the SMTP-Server?

Thanks

   const test_server = new SMTPServer({
        secure: false,
        logger: false,
        disabledCommands: ['AUTH', 'STARTTLS'],

        onData: function(stream, session, callback) {
                var mailparser = new MailParser();
                mailparser.on('headers', headers => {
                        console.log(headers.get('subject'));
                });
                mailparser.on('data', data => {
                        console.log(data.text);
                    });
                console.log(data.text);
                console.log(headers.get('subject'));
                stream.pipe(mailparser);
                stream.on('end', callback);
                }
     });
   test_server.listen("2600", this.host);

**Comment by mattgaspar** [comment]
I think you need to use the "end" event.

```
const test_server = new SMTPServer({
    secure: false,
    logger: false,
    disabledCommands: ['AUTH', 'STARTTLS'],

    onData: function (stream, session, callback) {
        var subject, text;
        var mailparser = new MailParser();

        mailparser.on('headers', headers => {
            subject = headers.get('subject');
        });

        mailparser.on('data', data => {
            if (data.type === 'text') {
                text = data.text;
            }
        });

        mailparser.on('end', () => {
            console.log(subject);
            console.log(text);
        });

        stream.pipe(mailparser);
        stream.on('end', callback);
    }
});

test_server.listen(2600);
```

**Comment by ceraz68** [comment]
Thanks a lot mattgaspar for looking at my example.

I completely forgot to add the mailparser.on ('end') event. I was glued to the nodemailer mailparser wiki which doesn't mention the end event ... it's so obvious !!

That solved my problem :-)
