### ISSUE TITLE
Attachments with uuencode transfer encoding not being decoded

### ISSUE THREAD

**Issue by tajinder** [nodemailer/mailparser#251]
Mailparser is unable to decode attachment having uuencode transfer encoding

**Comment by andris9** [comment]
Does this occur on parsing a recent email or does it happen when processing some old archived emails? Mailparser used to have uuencoded attachment support but uuencoded attachments stopped being a thing arount 1996.

**Comment by andris9** [comment]
uuencoded support was provided by [uue](https://www.npmjs.com/package/uue) module. As uuencoded attachments are parts of plaintext then you can run the uuencoding step yourself using the uue module over the plaintext content (if present). If uuencode is more widely supported then I thought then I guess it could be handled by Mailparser as well.
