### ISSUE TITLE
"input.once is not a function"

### ISSUE THREAD

**Issue by iv-med** [nodemailer/mailparser#253]
Hi everybody,
I have a trouble with working on  simpleParser function.
I have the next error:
 "errorType": "TypeError",
  "errorMessage": "input.once is not a function",
  "trace": [
    "TypeError: input.once is not a function",
    "    at module.exports (/var/task/node_modules/mailparser/lib/simple-parser.js:113:14)",
    "    at Response.<anonymous> (/var/task/index.js:21:7)",

**Comment by axyl** [comment]
I'm having the same issue with version 2.7.7 

Straight out of the box..

const mailparser= require('mailparser').simpleParser;
...
let parsedEmail= await mailparser(email);
