### ISSUE TITLE
Double encoded messages

### ISSUE THREAD

**Issue by tajinder** [nodemailer/mailparser#258]
We have some incoming messages which are encoded twice. Once in unicode and from UTF-16. The mailparser is decoding it only once and we end up with a utf-16 html.

**Comment by andris9** [comment]
Could you provide an example of such message?

**Comment by tajinder** [comment]
Sorry for the delay, I was getting the sample message I could share with you.

`From: BEU ContractManagement HAM <BEU.ContractManagement.HAM@bunge.com>
To: BEU ContractManagement HAM <BEU.ContractManagement.HAM@bunge.com>
Subject: FWD: CN MC:0060401369 14.04.2020 Soyabrokers V.O.F.
Thread-Topic: CN MC:0060401369 14.04.2020 Soyabrokers V.O.F.
Thread-Index: AQKvOwPR/lO8ZrZnKnzxEMajE4Ck4gIdldQE
Date: Wed, 15 Apr 2020 08:26:16 +0000
Message-ID: <1586939176323.f156d27ae591a@bunge.com>
References: <msn_9588715@5e96a2ff00001a66.GEN-NT-FAX11.eu.dir.bunge.com>
In-Reply-To: <msn_9588715@5e96a2ff00001a66.GEN-NT-FAX11.eu.dir.bunge.com>
Reply-To: BEU ContractManagement HAM <BEU.ContractManagement.HAM@bunge.com>
Content-Language: de-DE
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
X-MS-Exchange-Organization-RecordReviewCfmType: 0
x-sedna-version: v20200415-0000
Content-Type: multipart/alternative;
	boundary="_000_1586939176323f156d27ae591abungecom_"
MIME-Version: 1.0

--_000_1586939176323f156d27ae591abungecom_
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

DQoNCiAgX19fX18NCg0KR2VyZC1DaHJpc3RpYW4gTHVlaHINCkNvbnRyYWN0IEFkbWluIEhBTQ0K
SGFtYnVyZywgR2VybWFueQ0KT2ZmaWNlOiArNDkgNDAgODIyMiAxNyAxMzgNCiA8aHR0cDovL3d3
dy5idW5nZS5jb20uYnIvQXBwX1RoZW1lcy9JbWFnZW5zL2xvZ28tYnVuZ2UucG5nPg0KDQoNCg0K
LS0tLS0tLS0tLS0gT3JpZ2luYWwgTWVzc2FnZSAtLS0tLS0tLS0tLQ0KRnJvbTogIkJFVV9CQVRD
SCBCRVVfQkFUQ0giIDxCRVUuU0FQLkJBU0lTQGJ1bmdlLmNvbT4NCkRhdGU6IFdlZG5lc2RheSwg
QXByaWwgMTV0aCAyMDIwIGF0IDg6MDAgYW0NClN1YmplY3Q6IENOIE1DOjAwNjA0MDEzNjkgMTQu
MDQuMjAyMCBTb3lhYnJva2VycyBWLk8uRi4NClRvOiA8QkVVLkNPTlRSQUNUTUFOQUdFTUVOVC5I
QU1AQlVOR0UuQ09NPg0KQ2M6DQoNCg0KDQogICA8aHRtbD4gPGhlYWQ+IDxtZXRhIGh0dHAtZXF1
aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0idGV4dC9odG1sOyBjaGFyc2V0PXV0Zi0xNiI+IDwv
aGVhZD4gPGJvZHk+IEdyZWV0aW5ncywgUGxlYXNlIGZpbmQgYXR0YWNoZWQgeW91ciBjcmVkaXQg
bm90ZS4gPHA+PC9wPiA8cD48L3A+IDxwPjwvcD4gPHA+QnVuZ2UgRXhlY3V0aW9uIDwvcD4gPHA+
PC9wPiA8cD48L3A+IDxkaXYgc3R5bGU9ImZvbnQtc2l6ZTo5cHQ7IGZvbnQtZmFtaWx5OidDYWxp
YnJpJyxzYW5zLXNlcmlmOyI+PGJyPiBUaGlzIG1lc3NhZ2UgaXMgaW50ZW5kZWQgb25seSBmb3Ig
dGhlIG5hbWVkIHJlY2lwaWVudCBhbmQgbWF5IGNvbnRhaW4gY29uZmlkZW50aWFsLCBwcm9wcmll
dGFyeSBvciBsZWdhbGx5IHByaXZpbGVnZWQgaW5mb3JtYXRpb24uPGJyPiBObyBjb25maWRlbnRp
YWxpdHkgb3IgcHJpdmlsZWdlIGlzIHdhaXZlZCBvciBsb3N0IGJ5IGFueSBtaXNkaXJlY3RlZCB0
cmFuc21pc3Npb24uPGJyPiBJZiB5b3UgcmVjZWl2ZWQgdGhpcyBtZXNzYWdlIGluIGVycm9yLCBw
bGVhc2Ugbm90aWZ5IHVzIGltbWVkaWF0ZWx5IGJ5IHRlbGVwaG9uZSBhdCAmIzQzOzEgMzE0IDI5
Mi0yMDAwIGFuZCBpbW1lZGlhdGVseSBkZWxldGUgdGhpcyBtZXNzYWdlIGZyb20geW91ciBzeXN0
ZW0uPGJyPiBJZiB5b3UgYXJlIG5vdCB0aGUgaW50ZW5kZWQgcmVjaXBpZW50LCB5b3UgbXVzdCBu
b3QgdXNlLCBkaXNjbG9zZSwgZGlzdHJpYnV0ZSBvciBjb3B5IGFueSBwYXJ0IG9mIHRoaXMgbWVz
c2FnZS4gPC9kaXY+IDwvYm9keT4gPC9odG1sPg0KDQo=

--_000_1586939176323f156d27ae591abungecom_
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64

PGh0bWw+DQo8aGVhZD4NCjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0i
dGV4dC9odG1sOyBjaGFyc2V0PXV0Zi04Ij4NCjwvaGVhZD4NCjxib2R5Pg0KPGRpdiBpZD0iU0VE
TkEtQzBNUDA1MyIgc3R5bGU9ImZvbnQtZmFtaWx5OiAnLWFwcGxlLXN5c3RlbScsIEJsaW5rTWFj
U3lzdGVtRm9udCwgJ1NlZ29lIFVJJywgUm9ib3RvLA0KICAnSGVsdmV0aWNhIE5ldWUnLCBBcmlh
bCwgc2Fucy1zZXJpZiwgJ0FwcGxlIENvbG9yIEVtb2ppJywgJ1NlZ29lIFVJIEVtb2ppJywNCiAg
J1NlZ29lIFVJIFN5bWJvbCcsICdOb3RvIENvbG9yIEVtb2ppJywg5b6u6L2v6ZuF6buRLCAnTWlj
cm9zb2Z0IFlhSGVpIE5ldycsDQogICdNaWNyb3NvZnQgWWFoZWknLCAnUGluZ0ZhbmcgVEMnLCDl
rovkvZMsIFNpbVN1biwgU2ltSGVpLCBEZW5nWGlhbjsgZm9udC1zaXplOiAxcmVtOyB3b3JkLWJy
ZWFrOiBicmVhay13b3JkOyBvdmVyZmxvdy13cmFwOiBicmVhay13b3JkOyI+DQo8ZGl2IGlkPSJT
RUROQS1DME1QMDUzIiBzdHlsZT0id29yZC1icmVhazogYnJlYWstd29yZDsgZm9udC1mYW1pbHk6
ICZxdW90OyB1bmRlZmluZWQ6IC1hcHBsZS1zeXN0ZW0mcXVvdDsgdW5kZWZpbmVkOiAsJnF1b3Q7
IHVuZGVmaW5lZDogYmxpbmttYWNzeXN0ZW1mb250JnF1b3Q7IHVuZGVmaW5lZDogLCZxdW90OyB1
bmRlZmluZWQ6IHNlZ29ldWkmcXVvdDsgdW5kZWZpbmVkOiAsJnF1b3Q7IHVuZGVmaW5lZDogcm9i
b3RvJnF1b3Q7IHVuZGVmaW5lZDogLCZxdW90OyB1bmRlZmluZWQ6IGhlbHZldGljYW5ldWUmcXVv
dDsgdW5kZWZpbmVkOiAsJnF1b3Q7IHVuZGVmaW5lZDogYXJpYWwmcXVvdDsgdW5kZWZpbmVkOiAs
c2Fucy1zZXJpZiwmcXVvdDsgdW5kZWZpbmVkOiBhcHBsZWNvbG9yZW1vamkmcXVvdDsgdW5kZWZp
bmVkOiAsJnF1b3Q7IHVuZGVmaW5lZDogc2Vnb2V1aWVtb2ppJnF1b3Q7IHVuZGVmaW5lZDogLCZx
dW90OyB1bmRlZmluZWQ6IHNlZ29ldWlzeW1ib2wmcXVvdDsgdW5kZWZpbmVkOiAsJnF1b3Q7IHVu
ZGVmaW5lZDogbm90b2NvbG9yZW1vamkmcXVvdDsgdW5kZWZpbmVkOiAsLCZxdW90OyB1bmRlZmlu
ZWQ6IG1pY3Jvc29mdHlhaGVpbmV3JnF1b3Q7IHVuZGVmaW5lZDogLCZxdW90OyB1bmRlZmluZWQ6
IG1pY3Jvc29mdHlhaGVpJnF1b3Q7IHVuZGVmaW5lZDogLCZxdW90OyB1bmRlZmluZWQ6IHBpbmdm
YW5ndGMmcXVvdDsgdW5kZWZpbmVkOiAsLCZxdW90OyB1bmRlZmluZWQ6IHNpbXN1biZxdW90OyB1
bmRlZmluZWQ6ICwmcXVvdDsgdW5kZWZpbmVkOiBzaW1oZWkmcXVvdDsgdW5kZWZpbmVkOiAsJnF1
b3Q7IHVuZGVmaW5lZDogZGVuZ3hpYW4mcXVvdDsgZm9udC1zaXplOiAxcmVtOyBvdmVyZmxvdy13
cmFwOiBicmVhay13b3JkOyI+DQo8ZGl2Pjxicj4NCjxicj4NCjxociBzdHlsZT0idXNlci1zZWxl
Y3Q6IG5vbmU7IC1vLXVzZXItc2VsZWN0OiBub25lOyAtbW96LXVzZXItc2VsZWN0OiBub25lOyAt
a2h0bWwtdXNlci1zZWxlY3Q6IG5vbmU7IC13ZWJraXQtdXNlci1zZWxlY3Q6IG5vbmU7IC1tcy11
c2VyLXNlbGVjdDogbm9uZTsgYnJlYWstYWZ0ZXI6IGF2b2lkOyBjbGVhcjogYm90aDsgaGVpZ2h0
OiAycHg7IGNvbG9yOiAjMDAwOyBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwOyI+DQo8ZGl2PjxzdHJv
bmcgc3R5bGU9ImZvbnQtd2VpZ2h0OiA3MDA7Ij5HZXJkLUNocmlzdGlhbiBMdWVocjwvc3Ryb25n
PjwvZGl2Pg0KPGRpdj5Db250cmFjdCBBZG1pbiBIQU08L2Rpdj4NCjxkaXY+SGFtYnVyZywgR2Vy
bWFueTwvZGl2Pg0KPGRpdj48c3Bhbj5PZmZpY2U6ICYjNDM7NDkgNDAgODIyMiAxNyAxMzg8L3Nw
YW4+PC9kaXY+DQo8ZGl2PjxpbWcgc3JjPSJodHRwOi8vd3d3LmJ1bmdlLmNvbS5ici9BcHBfVGhl
bWVzL0ltYWdlbnMvbG9nby1idW5nZS5wbmciIHN0eWxlPSJvYmplY3QtZml0OiBzY2FsZS1kb3du
OyBwb3NpdGlvbjogcmVsYXRpdmU7IG1heC13aWR0aDogMTAwJTsiPjwvZGl2Pg0KPGJyPg0KPGJy
Pg0KPGJyPg0KLS0tLS0tLS0tLS0gT3JpZ2luYWwgTWVzc2FnZSAtLS0tLS0tLS0tLTxicj4NCkZy
b206ICZxdW90O0JFVV9CQVRDSCBCRVVfQkFUQ0gmcXVvdDsgJmx0O0JFVS5TQVAuQkFTSVNAYnVu
Z2UuY29tJmd0Ozxicj4NCkRhdGU6IFdlZG5lc2RheSwgQXByaWwgMTV0aCAyMDIwIGF0IDg6MDAg
YW08YnI+DQpTdWJqZWN0OiBDTiBNQzowMDYwNDAxMzY5IDE0LjA0LjIwMjAgU295YWJyb2tlcnMg
Vi5PLkYuPGJyPg0KVG86ICZsdDtCRVUuQ09OVFJBQ1RNQU5BR0VNRU5ULkhBTUBCVU5HRS5DT00m
Z3Q7PGJyPg0KQ2M6IDxicj4NCjxicj4NCjxibG9ja3F1b3RlIGNsYXNzPSJyZXBseS1xdW90ZSIg
c3R5bGU9ImJvcmRlci1sZWZ0OiBzb2xpZCAycHggI2FlYjhiNzsgbWFyZ2luLWxlZnQ6IDA7IHBh
ZGRpbmctbGVmdDogNXB4OyBtYXJnaW4tcmlnaHQ6IDBweDsiPg0KPGRpdj4mbHQ7aHRtbCZndDsg
Jmx0O2hlYWQmZ3Q7ICZsdDttZXRhIGh0dHAtZXF1aXY9JnF1b3Q7Q29udGVudC1UeXBlJnF1b3Q7
IGNvbnRlbnQ9JnF1b3Q7dGV4dC9odG1sOyBjaGFyc2V0PXV0Zi0xNiZxdW90OyZndDsgJmx0Oy9o
ZWFkJmd0OyAmbHQ7Ym9keSZndDsgR3JlZXRpbmdzLCBQbGVhc2UgZmluZCBhdHRhY2hlZCB5b3Vy
IGNyZWRpdCBub3RlLiAmbHQ7cCZndDsmbHQ7L3AmZ3Q7ICZsdDtwJmd0OyZsdDsvcCZndDsgJmx0
O3AmZ3Q7Jmx0Oy9wJmd0OyAmbHQ7cCZndDtCdW5nZSBFeGVjdXRpb24gJmx0Oy9wJmd0OyAmbHQ7
cCZndDsmbHQ7L3AmZ3Q7ICZsdDtwJmd0OyZsdDsvcCZndDsgJmx0O2RpdiBzdHlsZT0mcXVvdDtm
b250LXNpemU6OXB0OyBmb250LWZhbWlseTonQ2FsaWJyaScsc2Fucy1zZXJpZjsmcXVvdDsmZ3Q7
Jmx0O2JyJmd0Ow0KIFRoaXMgbWVzc2FnZSBpcyBpbnRlbmRlZCBvbmx5IGZvciB0aGUgbmFtZWQg
cmVjaXBpZW50IGFuZCBtYXkgY29udGFpbiBjb25maWRlbnRpYWwsIHByb3ByaWV0YXJ5IG9yIGxl
Z2FsbHkgcHJpdmlsZWdlZCBpbmZvcm1hdGlvbi4mbHQ7YnImZ3Q7IE5vIGNvbmZpZGVudGlhbGl0
eSBvciBwcml2aWxlZ2UgaXMgd2FpdmVkIG9yIGxvc3QgYnkgYW55IG1pc2RpcmVjdGVkIHRyYW5z
bWlzc2lvbi4mbHQ7YnImZ3Q7IElmIHlvdSByZWNlaXZlZCB0aGlzIG1lc3NhZ2UgaW4gZXJyb3Is
DQogcGxlYXNlIG5vdGlmeSB1cyBpbW1lZGlhdGVseSBieSB0ZWxlcGhvbmUgYXQgJmFtcDsjNDM7
MSAzMTQgMjkyLTIwMDAgYW5kIGltbWVkaWF0ZWx5IGRlbGV0ZSB0aGlzIG1lc3NhZ2UgZnJvbSB5
b3VyIHN5c3RlbS4mbHQ7YnImZ3Q7IElmIHlvdSBhcmUgbm90IHRoZSBpbnRlbmRlZCByZWNpcGll
bnQsIHlvdSBtdXN0IG5vdCB1c2UsIGRpc2Nsb3NlLCBkaXN0cmlidXRlIG9yIGNvcHkgYW55IHBh
cnQgb2YgdGhpcyBtZXNzYWdlLiAmbHQ7L2RpdiZndDsgJmx0Oy9ib2R5Jmd0OyAmbHQ7L2h0bWwm
Z3Q7DQo8L2Rpdj4NCjwvYmxvY2txdW90ZT4NCjwvZGl2Pg0KPC9kaXY+DQo8L2Rpdj4NCjwvYm9k
eT4NCjwvaHRtbD4NCg==

--_000_1586939176323f156d27ae591abungecom_--
`

**Comment by andris9** [comment]
@tajinder I don't see what is wrong with this message? All parsers, including mailparser seem to handle it correctly?

**Comment by tajinder** [comment]
@andris9 Sorry , seems like my team provided with wrong sample message, I will try to get you a correct one.
However, I tried debugging and I reach iconv-list/lib/index.js line 106 where it throws error
Encoding not recognized 'unicode'
