### ISSUE TITLE
Is there harm in calling release() early?

### ISSUE THREAD

**Issue by nickzelei** [nodemailer/mailparser#260]
[Reference Doc](https://nodemailer.com/extras/mailparser/#attachment-object-1)

I've been looking through the code and I think the answer is yes due to how the Mailparser handles the `curNode` property on the class.

I am after collecting all of the attachment streams and writing them all to files asynchronously. But due to the parser not continuing to the next attachment until `release` is called, this isn't really possible. 

I tried calling `release()` early and it worked! But I'm worried I may hit some race condition with a large file in the future.

```
async function getAttachments(inputStream) {
  return new Promise((resolve, reject) => {
    const attachments = [];
    const mailParser = new mailparser.MailParser();

    mailParser.on('data', (data) => {
      if (data.type !== 'attachment') {
        return;
      }
      if (!data.cid) {
        data.release();
        return;
      }
      attachments.push(data);
    });
    mailParser.on('error', err => reject(err));
    mailParser.on('end', () => resolve(attachments));
  });
}

async function foo(inputStream) {
  const attachments = await getAttachments(inputStream);
  for (const attachment of attachments) {
    const writeStream = fs.createWriteStream(attachment.cid);
    attachment.content.pipe(writeStream);
  }
}
```

In the real world the idea is to start streaming the contents as soon as the data is emitted, but the problem still persists in that I'd like the parser to being processing the next attachment while my code is streaming the previous one to disk. 
The way I understand the parser though is it will not begin processing the next attachment until my code has fully streamed the previous one.

**Comment by andris9** [comment]
You can call `data.release()` any time you like. It is just a signal marker that allows mailparser to move to next attachment once current one is processed. You can not process attachments in parallel as the message is processed as a single stream. You'd want to delay calling `release()` if processing the attachment takes time, eg. if you are writing it to S3 or doing some other slower operations on the attachment stream.
