### ISSUE TITLE
MailParser block forever with email multipart / rfc822 when bad closing mutli part boundary

### ISSUE THREAD

**Issue by acemtp** [nodemailer/mailparser#263]
cPanel (https://cpanel.net) send bad format email that cause simpleParser block forever.

As you can see in the following test, the closing tag of boundary should ended with a -- that is missing in cPanel email.

I imagine the parser is waiting forever the "--".

```
'Simple with part as rfc822 with bad closing boundary': test => {
        let encodedText =
            `Delivered-To: xxxx@gmail.com
Date: Wed, 03 Jun 2020 22:50:46 GMT
From: "cPanel on vps17201.sdfsfsd.com" <cpanel@sdfdsfs.sdfsdffs.com>
Message-Id: <sdfsdfs.v8A6D9BhtMalmPG8@vps17201.inmotionhosting.com>
Subject: [vps17201.sfsfsdfds.com] cPanel & WHM update failure in upcp script
To: <sfsdfsfsd@gmail.com>
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088"

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: multipart/alternative; boundary="alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971"

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: multipart/related; boundary="related-Cpanel::Email::Object-28634-1591224646-0.29282857359793"

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<body></body>

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793--

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971--

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: text/plain; charset="utf-8"; x-unix-mode=0600; name="update_log.txt"
Content-Disposition: attachment; filename="update_log.txt"
Content-Transfer-Encoding: base64

Z2xvcA==
--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088`,
            mail = Buffer.from(encodedText, 'utf-8');

        let mailparser = new MailParser();
        mailparser.end(mail);
        mailparser.on('data', () => false);
        mailparser.on('end', () => {
            test.equal(mailparser.text, '\nSubject: OK\n\nok');
            test.done();
        });
    },
```

**Comment by andris9** [comment]
Are you using the latest version of Mailparser? Similar issue was fixed some time ago

**Comment by acemtp** [comment]
DAMNED! You right, i was in 2.7.1... forget to update before testing... sorry

**Comment by acemtp** [comment]
Okay, just adding a new line at the end of the email make the parser freeze completely, even on the latest version. (we received an email like that).

Here is the test:

`'Simple with part as rfc822 with bad closing boundary': test => {
        let encodedText =
            `Delivered-To: xxxx@gmail.com
Date: Wed, 03 Jun 2020 22:50:46 GMT
From: "cPanel on vps17201.sdfsfsd.com" <cpanel@sdfdsfs.sdfsdffs.com>
Message-Id: <sdfsdfs.v8A6D9BhtMalmPG8@vps17201.inmotionhosting.com>
Subject: [vps17201.sfsfsdfds.com] cPanel & WHM update failure in upcp script
To: <sfsdfsfsd@gmail.com>
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088"

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: multipart/alternative; boundary="alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971"

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: multipart/related; boundary="related-Cpanel::Email::Object-28634-1591224646-0.29282857359793"

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<body></body>

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793--

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971--

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: text/plain; charset="utf-8"; x-unix-mode=0600; name="update_log.txt"
Content-Disposition: attachment; filename="update_log.txt"
Content-Transfer-Encoding: base64

Z2xvcA==
--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
`,
            mail = Buffer.from(encodedText, 'utf-8');

        let mailparser = new MailParser();
        mailparser.end(mail);
        mailparser.on('data', () => false);
        mailparser.on('end', () => {
            test.equal(mailparser.text, '\nSubject: OK\n\nok');
            test.done();
        });
    },`

**Comment by acemtp** [comment]
This case freeze also :

    'Simple with part as rfc822 with bad closing boundary': test => {
            let encodedText =
                `Delivered-To: xxxx@gmail.com
    Date: Wed, 03 Jun 2020 22:50:46 GMT
    From: "cPanel on vps17201.sdfsfsd.com" <cpanel@sdfdsfs.sdfsdffs.com>
    Message-Id: <sdfsdfs.v8A6D9BhtMalmPG8@vps17201.inmotionhosting.com>
    Subject: [vps17201.sfsfsdfds.com] cPanel & WHM update failure in upcp script
    To: <sfsdfsfsd@gmail.com>
    Mime-Version: 1.0
    Content-Type: multipart/mixed; boundary="mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088"
    
    --mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
    Content-Type: multipart/alternative; boundary="alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971"
    
    --alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: quoted-printable
    
    Test
    
    --alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
    Content-Type: multipart/related; boundary="related-Cpanel::Email::Object-28634-1591224646-0.29282857359793"
    
    --related-Cpanel::Email::Object-28634-1591224646-0.29282857359793
    Content-Type: text/html; charset=utf-8
    Content-Transfer-Encoding: quoted-printable
    
    <body></body>
    
    --related-Cpanel::Email::Object-28634-1591224646-0.29282857359793
    
    --related-Cpanel::Email::Object-28634-1591224646-0.29282857359793--
    
    --alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971--
    
    --mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
    Content-Type: text/plain; charset="utf-8"; x-unix-mode=0600; name="update_log.txt"
    Content-Disposition: attachment; filename="update_log.txt"
    Content-Transfer-Encoding: base64
    
    Z2xvcA==
    `,
                mail = Buffer.from(encodedText, 'utf-8');
    
            let mailparser = new MailParser();
            mailparser.end(mail);
            mailparser.on('data', () => false);
            mailparser.on('end', () => {
                test.equal(mailparser.text, '\nSubject: OK\n\nok');
                test.done();
            });
        },

**Comment by andris9** [comment]
I looked into the provided test cases and it seems the tests are a bit lacking. When using MailParser you have to consume and acknowledge attachments, otherwise MailParser will stay waiting. SimpleParser handles this automatically by buffering attachments into memory (so there is no need to process anything).

See the updated (and passing) test cases [here](https://github.com/nodemailer/mailparser/blob/1ce756feb982a6aab5f19396b42f492266260147/test/cpanel-test.js#L51-L57).

**Comment by acemtp** [comment]
Thank you for the update

**Comment by peernohell** [comment]
Hi Andris,

I just try the latest test case provided by acemtp and replace `mailparser.on('data'` and it's seems to continue to freeze.

Here is the example I have added into mail-parser-test.js

```javascript
module.exports['Simple with part as rfc822 with bad closing boundary'] = test => {
    let encodedText =
        `Delivered-To: xxxx@gmail.com
Date: Wed, 03 Jun 2020 22:50:46 GMT
From: "cPanel on vps17201.sdfsfsd.com" <cpanel@sdfdsfs.sdfsdffs.com>
Message-Id: <sdfsdfs.v8A6D9BhtMalmPG8@vps17201.inmotionhosting.com>
Subject: [vps17201.sfsfsdfds.com] cPanel & WHM update failure in upcp script
To: <sfsdfsfsd@gmail.com>
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088"

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: multipart/alternative; boundary="alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971"

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971
Content-Type: multipart/related; boundary="related-Cpanel::Email::Object-28634-1591224646-0.29282857359793"

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<body></body>

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793

--related-Cpanel::Email::Object-28634-1591224646-0.29282857359793--

--alternative-Cpanel::Email::Object-28634-1591224646-0.846610436809971--

--mixed-Cpanel::Email::Object-28634-1591224646-0.368578683442088
Content-Type: text/plain; charset="utf-8"; x-unix-mode=0600; name="update_log.txt"
Content-Disposition: attachment; filename="update_log.txt"
Content-Transfer-Encoding: base64

Z2xvcA==
`,
    mail = Buffer.from(encodedText, 'utf-8');

    let mailparser = new MailParser();
    mailparser.end(mail);

    mailparser.on('data', (c) => {
        if (c && typeof c.release === 'function') {
            // stream attachment content to /dev/null
            c.content.on('data', () => false);
            c.content.on('end', () => c.release());
        }
    });

    mailparser.on('end', () => {
        test.equal(mailparser.text, '\nSubject: OK\n\nok');
        test.done();
    });
};
```
![image](https://user-images.githubusercontent.com/119765/128891100-94ec8eb7-497f-474d-bb74-6de4d46b8865.png)

Maybe I forgot something?
Just as a reminder in this example, the closing boundary is totally missing.

**Comment by andris9** [comment]
@peernohell the test seems to throw because `AssertionError: 'Test\n' == '\nSubject: OK\n\nok'` and not because it would freeze?

**Comment by peernohell** [comment]
I'm really sorry, I didn't check the error correctly.
I fix the test and it work as expected. Thanks
