### ISSUE TITLE
Parsing message/global-delivery-status as attachment

### ISSUE THREAD

**Issue by DemChing** [nodemailer/mailparser#264]
The parser somehow treats `Content-Type: message/global-delivery-status` as an attachment instead of text.
Is there any way to specify a content type so that the parser would skip it or treat it as plaintext?

**Comment by andris9** [comment]
Can you provide an example eml file with such content so I could test how email clients in general treat that part?

**Comment by DemChing** [comment]
The base content type of the email is `multipart/report; report-type=delivery-status;` Some email clients will ignore that part while some will output it as text. You will receive that email when you fail to send an email (e.g. incorrect/inaccessible address).  

I've seen parts with content type like `message/global-delivery-status` or `message/delivery-status`.

Below shows the part that causes the error.
```
--cdc200ac-f631-4a4f-94a5-0a26178bec23
Content-Type: message/delivery-status

Reporting-MTA: dns;HK2APC01HT230.mail.protection.outlook.com
Received-From-MTA: dns;HK2PR01MB3156.apcprd01.prod.exchangelabs.com
Arrival-Date: Sun, 2 Aug 2020 01:06:38 +0000

Final-Recipient: rfc822;unable-to-access-email@gmail.com
Action: failed
Status: 5.1.1
Diagnostic-Code: smtp;550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1 https://support.google.com/mail/?p=NoSuchUser f3si3663859pfk.68 - gsmtp
Remote-MTA: dns;mx.google.com
X-Display-Name: unable-to-access-email@gmail.com
```

**Comment by andris9** [comment]
Treating such message part as an attachment is the correct behaviour as this is an embedded message object, not a plaintext content.
