### ISSUE TITLE
EXIM bounce messages, content part containing original message not parsed

### ISSUE THREAD

**Issue by eBulldog** [nodemailer/mailparser#270]
When parsing bounce messages received from EXIM v4.93 (default configuration), the final MIME content part contains the original message with content-type of "message/rfc822". This does not appear to be parsed when using simpleParser.

Interestingly I have two different eml files, one of them does indeed get parsed and appears as an attachment but it's content-type is false, and the other appears to get lost entirely (not showing as either attachment or part of the main mail object).

[emlfiles.zip](https://github.com/nodemailer/mailparser/files/4972319/emlfiles.zip)

**Comment by eBulldog** [comment]
The following code can be used with the eml files to confirm the behaviour:

```
const util = require('util');
const fs = require('fs');
const { equal } = require('assert');
const simpleParser = require('mailparser').simpleParser;

async function main() {
  let mail = await simpleParser(fs.createReadStream('doesntwork.eml'), {
    skipImageLinks: true, // do not convert CID attachments to data URL images
    skipHtmlToText: false, // generate plaintext from HTML if needed
    skipTextToHtml: false, // generate HTML from plaintext if needed
    skipTextLinks: true, // do not linkify links in plaintext content
    formatDateString: date => date.toUTCString() // format date in RFC822 embedded HTML head section
  });

  mail.attachments.forEach(function(attach){
    console.log(util.inspect(attach));
  });
}

main().catch(err => {
    console.log(err);
});
```

**Comment by andris9** [comment]
This happens because mailparser is mostly meant for email clients and message/rfc822 is in most cases not shown as an attachment but as an embedded message. If you'd look into the `mail.text` variable then it looks like this (see the `asd` block at the end of message):

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  ada@somedomain.com
    host mx1.somedomain.com [95.179.235.38]
    SMTP error from remote mail server after RCPT TO:<ada@somedomain.com>:
    550 5.1.1 <ada@somedomain.com>: Recipient address rejected:
    User unknown in virtual mailbox table


From: Adam <adam@someotherdomain.com>
Subject: asd
Date: Thu, 23 Jul 2020 13:13:38 GMT
To: ada@somedomain.com

asd
```

Compare it how Mac Mail shows the same message (also no attachment, `asd` is shown as part of message content):

![](https://cldup.com/0DdPCszmDh.png)

If for whatever reason you want to get message/rfc822 parts as attachments instead of embedded messages, then use `ignoreEmbedded: true` option. In this case `mail.text` would become:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  ada@somedomain.com
    host mx1.somedomain.com [95.179.235.38]
    SMTP error from remote mail server after RCPT TO:<ada@somedomain.com>:
    550 5.1.1 <ada@somedomain.com>: Recipient address rejected:
    User unknown in virtual mailbox table
```

and there would be an attachment listed:

```
{
  type: 'attachment',
  content: <Buffer 52 65 74 75 72 6e 2d 70 61 74 68 3a 20 3c 61 64 61 6d 40 73 6f 6d 65 6f 74 68 65 72 64 6f 6d 61 69 6e 2e 63 6f 6d 3e 0d 0a 52 65 63 65 69 76 65 64 3a ... 807 more bytes>,
  contentType: 'message/rfc822',
  partId: '3',
  release: null,
  headers: Map(1) { 'content-type' => { value: 'message/rfc822', params: {} } },
  checksum: '2bdee63574504a8ce5f86cd38676a3d0',
  size: 857
}
```

**Comment by eBulldog** [comment]
Thanks for the response @andris9 

I think your point is fair in the context of rendering in a client, it's the headers of the original message I actually need to establish the original unique MessageID. The ignoreEmbedded should do the trick although interestingly if I disable the transmission of original body in bounce message (in EXIM), the content-type becomes rfc822-headers which is consistently identified as an attachment.

The one issue though this doesn't explain is why the two eml's are parsed differently when their structure is consistent, and I'd suggest a content-type of 'false' is never desirable. A reminder that the kindaworks.eml identifies the message/rfc822 as an attachment with content-type: false yet doesntwork.eml does assume part of the body (and headers are lost).

Anyway it's closed, thanks ;)
