### ISSUE TITLE
Attachments broken with stream input

### ISSUE THREAD

**Issue by andreme** [nodemailer/mailparser#274]
I'm using mailparser to parse emails with large (1MB+) PDF attachments and the extracted PDFs are broken. I've tracked it to using streams as inputs rather than buffers.
Code to reproduce: 

```javascript
async function getAttachmentContentHash(input) {
	const mail = await require('mailparser').simpleParser(input);

	return require('crypto')
		.createHash('md5')
		.update(mail.attachments[0].content)
		.digest('hex');
}

async function test() {
	const fileStream = require('fs').createReadStream('test.eml');
	const fileBuffer = require('fs').readFileSync('test.eml');

	console.log('Stream:', await getAttachmentContentHash(fileStream));
	console.log('Buffer:', await getAttachmentContentHash(fileBuffer));
}

test();
```

Output:
```
Stream: 5bb2898fa108e3ea485baf4b4bff3cc2 <- wrong
Buffer: b04e1a850bb3654bdddcbd1fee3bb98a <- correct
```

Locally (on Windows 10) I'm only getting 1 difference in the file, but when for example reading from AWS S3 it's many differences, so I'm guessing it has something to do with the stream buffer size and stitching it back together in the mailparser?

I can provide the test.eml if necessary, but it contains data I can't make public.

**Comment by andreme** [comment]
This might be important:
```
Content-Type: application/octet-stream; name="x.pdf"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename="x.pdf"
```

It does **not** seem to happen with:
```
Content-Type: application/pdf; name="focus-st-ebro-may-2020-new.pdf"
Content-Disposition: attachment; filename="focus-st-ebro-may-2020-new.pdf"
Content-Transfer-Encoding: base64
```

**Comment by andris9** [comment]
I would need the referenced test.eml file to verify. Currently I can not reproduce this behavior.

**Comment by andreme** [comment]
@andris9 I've sent you an email with the test.eml

**Comment by andris9** [comment]
I can verify that checksums are different. The issue with this email is though that you are using quoted-printable encoding for a  binary attachment (the PDF file). Quoted-printable is not treated as lossless by mailparser and no guarantees are given - parsed result is good enough as long as the  textual content "looks" more or less the same as original input.

It happens to parse properly when reading entire email into a single buffer but this might not always be the case, you might still have issues with some specific bytes (eg. a single 0x0D might be normalized into 0x0A etc). To make sure that the file is parsed exactly as the source  always use base64 encoding for attachments.

**Comment by andreme** [comment]
Thanks - but I've got no control over how the email is created, my app is the receiver. Anyway, since using a Buffer works, it's not a problem for me. Just thought it should probably work the same for Stream and Buffer.

**Comment by andris9** [comment]
Yes, in general it should not matter if it is a stream or a buffer. And there actually is a bug but not in mailprser but in libqp that processes the quoted-printable file.

Bug occurs if input chunk from the stream ends with an equals sign. In this case an extra newline is added. This is super rare for text content to happen and the extra newline does not matter anyway but for binary files it is different.
