### ISSUE TITLE
Unpin dependency versions and commit npm.lock or yarn.lock

### ISSUE THREAD

**Issue by toymachiner62** [nodemailer/mailparser#280]
I don't see an npm.lock or yarn.lock file in this repo. It's recommended to commit that file and then allow your dependencies to to use the `^` so they automatically get minor/patch versions if consumers of mailparser want them.

**Comment by andris9** [comment]
Sorry, I like to fix all dependencies for my libraries and not use a lock file.

**Comment by toymachiner62** [comment]
Sounds good. The biggest advantage of doing it though is that I wouldn't have had to create a PR and have you create a new release just to update nodemailer. If it was a minor or patch version I can just update my yarn.lock file to use a higher version of one of your dependencies as long as it's within the "range" (using `^`).

**Comment by mpsijm** [comment]
I ran into the same issue waiting for #432 / #433 to be resolved, so here's another voice in favour of using the semver ranges: it helps getting security fixes to transitive dependencies to land at end-users sooner, and without having to release a new version yourself 🙂
