### ISSUE TITLE
Please publish new version with new nodemailer to fix vulnerability

### ISSUE THREAD

**Issue by cythrawll** [nodemailer/mailparser#283]
Nodemailer less than 6.4.16 has a vulnerability with HIGH SEVERITY: https://snyk.io/vuln/SNYK-JS-NODEMAILER-1038834

This repo seems to bring in the correct dependencies but has not been published.  Therefore projects upstream are bringing in a vulnerable version of nodemailer when installed. 

Please publish the version with 6.4.16.

Can you also please release a version on your 2.x branch with a secure version of nodemailer as well? I can't use the 3.x version due to license.

**Comment by bote795** [comment]
https://app.snyk.io/vuln/SNYK-JS-NODEMAILER-1296415

**Comment by andris9** [comment]
After reviewing the vulnerability there is no need to change anything in mailparser as the vulnerable parts of Nodemailer are not used and thus do not apply to mailparser.

**Comment by jrichiemx** [comment]
@andris9 
even if the risk is mitigated, a vulnerability scanner will report this as a vulnerability
