### ISSUE TITLE
attachments of type "message/delivery-status" not parsed

### ISSUE THREAD

**Issue by micktaiwan** [nodemailer/mailparser#300]
It seems that attachements of type "message/delivery-status" are not parsed anymore
https://runkit.com/micktaiwan/6116d77c870c05001b7da55c

compare it with 2.7.0
https://runkit.com/peernohell/5ab2989d25eebc001213c29d

**Comment by andris9** [comment]
Use option `keepDeliveryStatus:true`

**Comment by micktaiwan** [comment]
Thank you so much !
Is it documented somewhere ? I could not find it.

**Comment by peernohell** [comment]
Honestly the options should default to `true` or the  major version should be increase because it's a breaking change :(

**Comment by andris9** [comment]
It was changed by this PR in february: https://github.com/nodemailer/mailparser/pull/292

**Comment by andris9** [comment]
`message/delivery-status` previously did not have any special handling, this is why the change did not seem major back then. If you rely on this report to detect bounces then you could check how [EmailEngine](https://emailengine.app/) handles bounces with Mailparser as this approach is guaranteed to be stable.

**Comment by andris9** [comment]
Here’s the bounce detection code that uses Mailparser: https://github.com/postalsys/emailengine/blob/master/lib/bounce-detect.js

**Comment by peernohell** [comment]
Thanks a lot for all those information 🤩

**Comment by andris9** [comment]
Just for the record if anyone stumbles upon this issue in the future, here's an explanation how EmailEngine handles the bounce data: https://docs.emailengine.app/using-as-a-transactional-email-service/#bounce-detection
