### ISSUE TITLE
European Date parser JS issue

### ISSUE THREAD

**Issue by Inqnuam** [nodemailer/mailparser#304]
JS new Date() fails if date string contains European Time Zone word like CET, CEST, CEWT
to fix this in mail-parser.js removing theses values fixes the issue:

case 'date':
                    let orgValue = value
                    value = new Date(value);
                    if (isNaN(value)) {
                       
                        // date parsing failed :S
                        value = new Date(orgValue.replace(/CEST|CET|CEWT/gi, ""));
                    }
                    break;

**Comment by andris9** [comment]
Do you have an example source of such an email that uses such Date value?

**Comment by Inqnuam** [comment]
> Do you have an example source of such an email that uses such Date value?

Of course
How can I export that mail raw data ?

**Comment by andris9** [comment]
It's the same message you parse with mailparser. I would need to check the exact format and also which kind of client generated etc.

**Comment by Inqnuam** [comment]
> It's the same message you parse with mailparser. I would need to check the exact format and also which kind of client generated etc.

[failedDateParsing.txt](https://github.com/nodemailer/mailparser/files/7244081/failedDateParsing.txt)
Heres one of related mail in json format 
Parsed invalid date which points to new Date() is replaced by original received date string

**Comment by andris9** [comment]
Thanks. Could you provide the input for that data instead? Eg. the raw message in rfc822 (the eml file) format that you used to parse with mailparser?

**Comment by Inqnuam** [comment]
> Thanks. Could you provide the input for that data instead? Eg. the raw message in rfc822 (the eml file) format that you used to parse with mailparser?

I know nothing about mail formats and data, any tip to get that eml file?

**Comment by andris9** [comment]
this is the string or file that you provide to mailparser for parsing.

```
simpleParser(somehting, options, (err, parsed) => {});
```

I need the `something`

**Comment by Inqnuam** [comment]
> this is the string or file that you provide to mailparser for parsing.
> 
> ```
> simpleParser(somehting, options, (err, parsed) => {});
> ```
> 
> I need the `something`

Should I export this JS object ?
<img width="586" alt="Screenshot 2021-09-28 at 15 20 37" src="https://user-images.githubusercontent.com/69360379/135095031-8c50246d-801f-44e8-942a-122b6fb46c46.png">
<img width="583" alt="Screenshot 2021-09-28 at 15 20 54" src="https://user-images.githubusercontent.com/69360379/135095054-ddcdb6ea-5835-419f-abac-cb595ce505e9.png">

**Comment by andris9** [comment]
Fixed in v3.3.2
