### ISSUE TITLE
mailparser v3.6.0 package.json set {"html-to-text": "9.0.2"} is error

### ISSUE THREAD

**Issue by HbuJiaTian** [nodemailer/mailparser#325]
mailparser v3.6.0 package.json set {"html-to-text": "9.0.2"} is error.
html-to-text: "9.0.2" the version has the error like this:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/10797390/207012310-81d3d516-de67-4233-8586-36ef6baa4c08.png">

**Comment by andris9** [comment]
Which nodejs version are you using? Should be at least Node 16

**Comment by kennydifiore** [comment]
If you're changing your dependencies (e.g., min node version to 16), this is a breaking change and you should use proper semantic versioning and update your major version of your package to 4.0.0

**Comment by TonyRL** [comment]
You need to update your node js version to at least v14.
Nullish coalescing operator (??) is available since node v14.

**Comment by andris9** [comment]
See https://github.com/nodemailer/mailparser/issues/327#issuecomment-1352668239
