### ISSUE TITLE
Downgrade node engine to 14 

### ISSUE THREAD

**Issue by AgyaeyTiwari** [nodemailer/mailparser#327]
We are facing failures in product installs as this is a dependency of many mail plugins.
We are using 'email-templates' with node 14.

@andris9 Node Engine should never be updated in patch/minor release. **Either please remove it or keep it low as possible.**

**Comment by kennydifiore** [comment]
Related to: https://github.com/nodemailer/mailparser/issues/325

**Comment by andris9** [comment]
_mailparser_ predates _semver_ adoption – when I started with _mailparser_ almost no-one was using _semver_ yet (the spec did exist, though). The _mailparser_ versioning scheme for the past 12 years has been such that the major number indicates the incarnation version. This is how many times the core of _mailparser_ has been rewritten from scratch.

The engine upgrade requirement is unfortunate and unintentional. It happened when one of the dependencies of _mailparser_ started using the coalescing operator, and automated tests failed with node 14 and below. The best I can do right now is to remove the engine definition from package.json, so if your node version lower than 16 actually can handle running _mailparser_, you will not get a warning about the engine version.

**Comment by andris9** [comment]
Published a new mailparser version as mailparser@3.6.2 where package.json does not have the engine definition anymore.
