### ISSUE TITLE
Node 12 was dropped without a major version upgrade

### ISSUE THREAD

**Issue by alechirsch** [nodemailer/mailparser#328]
When html-to-text was upgraded to version 9, this package no longer supported node version 12. I see in the tests that node 12 was dropped after a test failure. When this happens you need to do a major npm version upgrade to avoid issues like this.

**Comment by andris9** [comment]
See this comment: https://github.com/nodemailer/mailparser/issues/327#issuecomment-1352668239

Tl; dr. Mailparser predates semver adoption and has never used semver versioning.
