### ISSUE TITLE
Missing documentation/types for some options

### ISSUE THREAD

**Issue by dumbasPL** [nodemailer/mailparser#331]
I've noticed that some mail parser options are undocumented and don't have types declared in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

some that I found:
```
keepDeliveryStatus: boolean
checksumAlgo: string
```

Is this intentional or just an oversight?

**Comment by andris9** [comment]
mailparser does not have official typings. You need to contact the guys maintaining the types directly.

**Comment by dumbasPL** [comment]
> mailparser does not have official typings. You need to contact the guys maintaining the types directly.

Sure, I'll add that myself then. But the documentation over at https://nodemailer.com/extras/mailparser/#options is still lacking these options.

**Comment by dumbasPL** [comment]
bump @andris9
