### ISSUE TITLE
Omitting quotes in parsed headers seems incorrect

### ISSUE THREAD

**Issue by neemah** [nodemailer/mailparser#339]
Given email with TO header (source):

```
To: "iepnewservice@" <iepnewservice@domain.com>,
 "kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1@domain.com"
 <kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1@domain.com>
```

We have code:
```
const mail = await simpleParser(
        mailRaw,
        { keepCidLinks: true },
      );

      console.log('Headers:');
      mail.headers.forEach((val, key) => {
        console.log(key, val);
      });
```

That produces this log:
```
to {
  value: [
    { address: 'iepnewservice@domain.com', name: 'iepnewservice@' },
    {
         address: 'kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1@domain.com',
         name: 'kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1'
    },
   html: '....',
   text: 'iepnewservice@ <iepnewservice@domain.com>, kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1 <kaiten+new-card-61fc0f99b3582667-b2313-c7695-l3759-a1@domain.com>'
]
```

Check the **text** value - it has no quotes surrounding the name part of **iepnewservice@**

We think that quotes should not be removed and keep the original string as it was in the source email

**Comment by andris9** [comment]
This is not possible as mailparser normalizes all addresses to a common base format and then uses these to generate the output. Comments, quotes, etc, do not survive the process.

**Comment by pennane** [comment]
Our team also faced confusion for why this is happening.

> This is not possible as mailparser normalizes all addresses to a common base format

I would argue that the `text` field should skip the normalization and use the unmodified header value if in anyway possible.
