### ISSUE TITLE
TypeScript types do not describe simpleParser's output when parsing email that have multiple headers of the same key

### ISSUE THREAD

**Issue by harrydshapiro** [nodemailer/mailparser#341]
I am experiencing a discrepancy between the output of simpleParser and what is supposed to be typed for `ParsedMail.headers.get()`.

The `ParsedMail` type's headers value is typed like so:
`type HeaderValue = string | string[] | AddressObject | Date | StructuredHeader;`

But when leveraging simpleParser to parse an email with multiple headers of the same key, the output is an array of whatever the type would be if there was only _one_ header with that key. So having two `Delivered-To` headers will lead to an output of type `AddressObject[]`, two `DKIM-Signature` headers will lead to an output type of `StructuredHeader[]`, etc. For example: 

```
"delivered-to": [
    {
        value: [
            {
                address: "emailAddress1@gmail.com",
                name: "",
            },
        ],
        html: '<span class="mp_address_group"><a href="mailto:emailAddress1@gmail.com" class="mp_address_email">emailAddress1@gmail.com</a></span>',
        text: "emailAddress1@gmail.com",
    },
    {
        value: [
            {
                address: "emailAddress2@gmail.com",
                name: "",
            },
        ],
        html: '<span class="mp_address_group"><a href="mailto:emailAddress2@gmail.com" class="mp_address_email">emailAddress2@gmail.com</a></span>',
        text: "emailAddress2@gmail.com",
    },
],
```

Since I know that this is a possibility in production, I have to handle it in code and override the TS errors that pop up as a result.

I would prefer to not publicly share the raw source of my emails in which I have seen this happen, but if you're a maintainer of `mailparser`, I'd happily send them to you privately (and - while I have you - thank you so much for your work!).

**Comment by andris9** [comment]
Mailparser does not have official TS support, you need to contact those people who maintain these types directly.
