### ISSUE TITLE
simpleParser doesn't decode body part 

### ISSUE THREAD

**Issue by Rabinzon** [nodemailer/mailparser#343]
It decode windows-1251 subject and headers but ignore content part.I didn't find any information in the documentation. How to fix it?

```
To: test@test.io
Subject: =?windows-1251?B?ze7i7uUg8e7u4fnl7ejlIPTu8Oz7ICLH4Org5+Dy/CDz8evz4/MiIPEg8eDp8uAgItHI0MjT0SDR5fDi6PEi?=
From: marketing@test.io
Reply-To: marketing@test.io
Date: Fri, 17 Mar 2023 15:14:45 +0300
Content-Type: text/plain; charset=windows-1251
Content-Transfer-Encoding: 8bit

Вами заполнена форма "Заказать услугу" на сайте

------------------------------------------

Сообщение сгенерировано автоматически.


```

![image](https://user-images.githubusercontent.com/8072488/231414794-20329d1f-b8db-4ea8-bf21-b496232eb03b.png)

**Comment by andris9** [comment]
You need to provide the original Buffer value. Seems like you use a string that is already unicode so the content is double-decodes
