### ISSUE TITLE
header decode issue

### ISSUE THREAD

**Issue by roundbishop** [nodemailer/mailparser#376]
Hello,

I’m reporting an issue where the decoding is not working properly.

The value of the header should be decoded as euc-kr, but the decoding does not work.

In the processHeaders method of processorHeader:

``` javascript
processHeaders(lines) {
    let headers = new Map();
    (lines || []).forEach(line => {
        let key = line.key;
        let value = ((this.libmime.decodeHeader(line.line) || {}).value || '').toString().trim();
        value = Buffer.from(value, 'binary').toString();
```

When line.line, passed to decodeHeader in this.libmime.decodeHeader, is modified with iconv.decode(line.line, 'euc-kr') to reflect the charset, it works well. and remove "Buffer.from(value, 'binary').toString();" code.

However, when this is not done, the characters are displayed incorrectly and appear garbled.

Please check this issue.

[issue.zip](https://github.com/user-attachments/files/17499606/issue.zip)

**Comment by andris9** [comment]
Unfortunately, there is no direct fix for this. It is impossible to reliably detect which encoding is used for 8-bit characters in the message headers. The standard (and default) encoding for message headers is UTF-8. Using non-UTF-8 8-bit characters in message headers is not compliant with the email standards.

There are thousands of possible code pages, not just EUC-KR, and Mailparser has no way of detecting which code page was used in these cases. Email clients handle this using heuristics based on the user's locale, but Mailparser, as a server-side component, does not have such mechanisms.

If you know that the emails you are receiving use a specific 8-bit character set in the headers, the recommended solution is to preprocess the headers (or the entire message) by using `iconv.decode` to convert the encoding before parsing the message with Mailparser.
