### ISSUE TITLE
feat: consider using `striptags` instead of `html-to-text` for performance reasons

### ISSUE THREAD

**Issue by titanism** [nodemailer/mailparser#377]
When using `v8-profiler-next` and `cpupro` we identified a bottleneck with `mailparser` underlying usage with `htmlToText`.

Alternatively, perhaps we could use `striptags` @andris9 instead as a more performant alternative?

<https://github.com/nodemailer/mailparser/blob/af0c1e6044643ee9c9590e3bac5ceaac2c5120a4/lib/mail-parser.js#L749>

**Comment by andris9** [comment]
[html-to-text](https://www.npmjs.com/package/html-to-text) does so much more than [striptags](https://www.npmjs.com/package/striptags) that these aren't really even compareable. I would suggest using the `skipHtmlToText` option instead if you have performance issues.
