### ISSUE TITLE
quoted-printable attachment missing some tabs

### ISSUE THREAD

**Issue by ornotnull** [nodemailer/mailparser#379]
Hello!

Prepared the example - mail.eml.gz
One file.csv attachment is encoded as quoted-printable.
After extraction it's missed some tabs delimiters.

missing-tabs.mjs - to run the example

`"A"     "field1"        "01/01/2024"    "field3 long"   "01/01/2024"    "01/01/2024""XYZ"       "long long field long long field"       "BBBBBBB"     "AA"    "00000" "AAAAAAAA"      "an other field"        "test"  "OO"    "00000" "00000000"      "CDE"   1       "00000" "000000"     0.01     0.02    0.03    0.04    0.05    0.06    "AAA BBB"       "0"
"A"     "field1"        "01/01/2024"    "field3 long"   "01/01/2024"    "01/01/2024""XYZ"       "long long field long long field"       "BBBBBBB"     "AA"    "00000""AAAAAAAA"       "an other field"        "test"  "OO"    "00000" "00000000"      "CDE"   1       "00000" "000000"     0.01     0.02    0.03    0.04    0.05    0.06    "AAA BBB"       "0"
"A"     "field1"        "01/01/2024"    "field3 long"   "01/01/2024"    "01/01/2024""XYZ"       "long long field long long field"       "BBBBBBB"     "AA"    "00000" "AAAAAAAA"      "an other field"        "test"  "OO"    "00000" "00000000"      "CDE"   1       "00000" "000000"     0.01     0.02    0.03    0.04    0.05    0.06    "AAA BBB"       "0"`

Tabs are missed here:
"01/01/2024""XYZ" (3 times)
"00000""AAAAAAAA" (once)

tested with the node v22.11.0 and mailparser@3.7.1

[missing-tabs.mjs.gz](https://github.com/user-attachments/files/17792006/missing-tabs.mjs.gz)
[mail.eml.gz](https://github.com/user-attachments/files/17792009/mail.eml.gz)

**Comment by ornotnull** [comment]
@nahne, thank you!

Confirm, your PR for libpq fixed this issue!

**Comment by andris9** [comment]
Could you try v3.7.2 to see if the fix helped?

**Comment by ornotnull** [comment]
@andris9, thank you!
This issue has been fixed in v3.7.2!
