### ISSUE TITLE
format=flowed does not work with quoted-printable encoding

### ISSUE THREAD

**Issue by asutherland** [nodemailer/mailparser#45]
Although use of quoted-printable with format-flowed is discouraged, Thunderbird does it anyways.

The simplest solution is to do the format=flowed transform after the quoted-printable decoding.  Here's a patch (with regrettable whitespace changes because my limited-fork already let js2-mode go to town...) that shows how that might go:

https://github.com/asutherland/mailparser/commit/f03b3a55f32fc63c50dc3e656864b695c71be2f9

I can provide a proper fix without the whitespace ugliness and with a test case, if you like.  The unit test would be straightforward; the b2g e-mail lib's test case for it is in this pull request: https://github.com/asutherland/gaia-email-libs-and-more/pull/1

**Comment by wiktor-k** [comment]
Is this issue really resolved? I'm parsing a [format=flowed quoted-printable message](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3Cf068f49d-7185-a49b-6404-8bbde5da2e97%40metacode.biz%3E/raw) and it seems like adding `format=flowed` disables un-quoting.

Example message (the same as above but minimized):

```
Subject: Re: Why hard wrap at 72 in lists
Message-ID: <f068f49d-7185-a49b-6404-8bbde5da2e97@metacode.biz>
Date: Tue, 22 Jan 2019 11:48:21 +0100
MIME-Version: 1.0
In-Reply-To: <372c8adf-d0ba-0cda-e56b-9538db2e99da@interia.pl>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

> The format=3Dflowed RFC supports having lines that are explicitly meant
> not to be wrapped (they call them "fixed lines") but looks like
> many format=3Dflowed MUAs don't give you a way to write such lines
> as you compose the email...

FastMail doesn't want to implement format=3Dflowed as it's extra work and=
=20
they want to focus on HTML mail (as evidenced by "HTML has mostly won"=20
in their post).
```

I'm parsing it using the following code:

```js
const simpleParser = require('mailparser').simpleParser;
const fs = require('fs');
simpleParser(fs.readFileSync('mail.eml')).then(parsed => console.log(parsed.text));
```

And it prints:

```
> The format=3Dflowed RFC supports having lines that are explicitly meant> not to be wrapped (they call them "fixed lines") but looks like
> many format=3Dflowed MUAs don't give you a way to write such lines
> as you compose the email...

FastMail doesn't want to implement format=3Dflowed as it's extra work and=
=20
they want to focus on HTML mail (as evidenced by "HTML has mostly won"=20
in their post).
```

It's not un-quoted.
