### ISSUE TITLE
Does not support iso-2022-jp?

### ISSUE THREAD

**Issue by chulgil** [nodemailer/mailparser#47]
Error occurs when i try to parse the subject IN mail header(mime type is iso-2022-jp)

**Comment by mazamachi** [comment]
I faced the same issue when parsing a mail encoded with iso-2022-jp.
I installed iconv as @andris9 says, but didn't fix the problem.

I found iconv has been removed from optional dependency. 
Currently is there any way to decode iso-2022-jp mail?

**Comment by andris9** [comment]
@mazamachi Yeah, sorry for that. I run my own applications on platforms without compilation support so I have moved away from native modules like node-iconv. You could use an older version of Mailparser though:

```
npm install mailparser@0.6.2 iconv --save
```

The older version has different api, see the docs for it [here](https://github.com/nodemailer/mailparser/blob/b8488c5b6a73920b58bcd2f62a5c3be115940fe4/README.md)
