### ISSUE TITLE
Unexpected behaviour of showAttachmentLinks-option

### ISSUE THREAD

**Issue by Reggino** [nodemailer/mailparser#61]
Hi Andris,

Once again, great work on your MIME and mail classes. 

Today i ran into an issue:

I tried to parse a MIME message with no HTML-part, but with attachments. Since there was no HTML, the option `showAttachmentLinks` didn't do anything: there was no HTML to append the links to and so the links where missing in the final output.

Maybe  `showAttachmentLinks` should force the existence of a `html` part in the result, when attachments are found?

**Comment by asbjornenge** [comment]
I'm also having this issue on v0.4.8. @Reggino was that fix ever merged?

**Comment by Reggino** [comment]
@see https://github.com/andris9/mailparser/pull/62

**Comment by asbjornenge** [comment]
@Reggino ah! Thanks :+1:
