### ISSUE TITLE
Text of email is not properly decoded

### ISSUE THREAD

**Issue by mbrio** [nodemailer/mailparser#86]
I'm testing against a gmail account, I've received a few emails from other sources, and have sent myself both text and html emails. When I parse the emails my `text` property always comes back with boundaries in place, and if it's an email with both HTML and text the property contains both:

Plain text:

```
--001a1136b5c069839604fa64cc09--
Here is a test of plain text
```

HTML + Plain text:

```
--089e0149d0e44917e904fa7682fc
Content-Type: text/plain; charset=UTF-8

Now here is an HTML version

--089e0149d0e44917e904fa7682fc
Content-Type: text/html; charset=UTF-8

<div dir="ltr">Now here is an HTML version</div>

--089e0149d0e44917e904fa7682fc--
```

Is this how the `text` property is supposed to behave? All other properties get properly parsed, just not the body.

**Comment by danbraik** [comment]
> In getting you the contents of the email I inadvertently fixed my own problem. I was using node-imap in conjunction with mailparser. My fetch call was only requesting the to, from, date, and subject headers, along with the text. Apparently when requesting only some headers the body of the email is no longer able to be parsed. **When I requested the email in its entirety it parsed correctly.**

Thank you, you saved my life !
